# Form implementation generated from reading ui file 'commanderui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Commander(object):
    def setupUi(self, Commander):
        Commander.setObjectName("Commander")
        Commander.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Commander)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Commander)
        QtCore.QMetaObject.connectSlotsByName(Commander)

    def retranslateUi(self, Commander):
        _translate = QtCore.QCoreApplication.translate
        Commander.setWindowTitle(_translate("Commander", "Form"))
